-- ============================================================================
-- 0047_game_prompts.sql — the games and what's in them
-- ============================================================================
-- Eleven games over the three mechanics in 0046. Kept in their own migration
-- for the same reason as the handbook sections: the list of prompts is the
-- part that will keep growing, and adding to it shouldn't touch the schema.

insert into public.games (slug, name, emoji, tagline, mode, rounds, sort_order) values
  ('would_you_rather', 'Would You Rather',      '🤔', 'Two bad options. Pick one.',                'match', 10, 10),
  ('this_or_that',     'This or That',          '⚡', 'Fast. Don''t think about it.',              'match', 12, 20),
  ('who_knows',        'Who Knows Who Better?', '🧠', 'One answers honestly. One guesses.',        'guess', 10, 30),
  ('guess_my_answer',  'Guess My Answer',       '🔮', 'How well do you actually know me?',         'guess', 10, 40),
  ('couple_trivia',    'Couple Trivia',         '🏆', 'Questions only the two of you can answer.', 'guess', 10, 50),
  ('finish_sentence',  'Finish My Sentence',    '✍️', 'They start it. You finish it. Then compare.','guess', 10, 60),
  ('remember',         'How Well Do You Remember…?', '🕰️', 'The details you swear you know.',     'guess', 10, 70),
  ('truth_or_dare',    'Truth or Dare',         '🎭', 'No scoring. Just do it.',                   'draw',  12, 80),
  ('twenty_questions', '20 Questions',          '2️⃣', 'Twenty, in a row, no deflecting.',          'draw',  20, 90),
  ('emoji_game',       'Emoji Guessing',        '😅', 'Spell it in emoji. They guess out loud.',   'draw',  12, 100),
  ('picture_game',     'Picture Guessing',      '🖼️', 'Describe a photo. They name it.',          'draw',  10, 110)
on conflict (slug) do update set
  name = excluded.name, emoji = excluded.emoji, tagline = excluded.tagline,
  mode = excluded.mode, rounds = excluded.rounds, sort_order = excluded.sort_order;

insert into public.game_prompts (couple_id, game_slug, body, option_a, option_b) values
  -- 🤔 Would You Rather ------------------------------------------------------
  (null, 'would_you_rather', 'Would you rather…', 'Never argue again', 'Never be bored again'),
  (null, 'would_you_rather', 'Would you rather…', 'Read my mind for a day', 'Have me read yours'),
  (null, 'would_you_rather', 'Would you rather…', 'A year apart, then forever', 'Forever, but always busy'),
  (null, 'would_you_rather', 'Would you rather…', 'Lose every photo of us', 'Lose every message'),
  (null, 'would_you_rather', 'Would you rather…', 'Always know the truth', 'Sometimes be spared it'),
  (null, 'would_you_rather', 'Would you rather…', 'Live somewhere loud and alive', 'Somewhere quiet and slow'),
  (null, 'would_you_rather', 'Would you rather…', 'Be the funny one', 'Be the one who''s always right'),
  (null, 'would_you_rather', 'Would you rather…', 'Cook every night', 'Wash up every night'),
  (null, 'would_you_rather', 'Would you rather…', 'Never text again', 'Never call again'),
  (null, 'would_you_rather', 'Would you rather…', 'Relive our first month', 'Fast-forward five years'),
  (null, 'would_you_rather', 'Would you rather…', 'A big wedding', 'A big house'),
  (null, 'would_you_rather', 'Would you rather…', 'Go to bed angry once', 'Argue until 4am'),
  (null, 'would_you_rather', 'Would you rather…', 'Be told exactly what I want', 'Work it out yourself'),
  (null, 'would_you_rather', 'Would you rather…', 'Holiday somewhere new every year', 'The same place we love'),
  (null, 'would_you_rather', 'Would you rather…', 'I sing badly in the car', 'I say nothing the whole drive'),

  -- ⚡ This or That ----------------------------------------------------------
  (null, 'this_or_that', 'Pick one', 'Morning', 'Night'),
  (null, 'this_or_that', 'Pick one', 'Beach', 'Mountains'),
  (null, 'this_or_that', 'Pick one', 'Call', 'Text'),
  (null, 'this_or_that', 'Pick one', 'Stay in', 'Go out'),
  (null, 'this_or_that', 'Pick one', 'Sweet', 'Spicy'),
  (null, 'this_or_that', 'Pick one', 'Plan it', 'Wing it'),
  (null, 'this_or_that', 'Pick one', 'Big party', 'Just us'),
  (null, 'this_or_that', 'Pick one', 'Film', 'Series'),
  (null, 'this_or_that', 'Pick one', 'Cook in', 'Order in'),
  (null, 'this_or_that', 'Pick one', 'Flowers', 'Food'),
  (null, 'this_or_that', 'Pick one', 'Loud music', 'Windows down, quiet'),
  (null, 'this_or_that', 'Pick one', 'Say it', 'Write it'),
  (null, 'this_or_that', 'Pick one', 'Early flight', 'Late flight'),
  (null, 'this_or_that', 'Pick one', 'Surprise me', 'Tell me first'),
  (null, 'this_or_that', 'Pick one', 'Cats', 'Dogs'),
  (null, 'this_or_that', 'Pick one', 'Tea', 'Coffee'),

  -- 🧠 Who Knows Who Better --------------------------------------------------
  (null, 'who_knows', 'What''s my comfort food?', null, null),
  (null, 'who_knows', 'What am I most likely to be late for?', null, null),
  (null, 'who_knows', 'What''s my worst habit?', null, null),
  (null, 'who_knows', 'What would I spend an unexpected £500 on?', null, null),
  (null, 'who_knows', 'What''s my go-to order?', null, null),
  (null, 'who_knows', 'What song do I secretly love?', null, null),
  (null, 'who_knows', 'What am I proudest of?', null, null),
  (null, 'who_knows', 'What annoys me fastest?', null, null),
  (null, 'who_knows', 'What would I never throw away?', null, null),
  (null, 'who_knows', 'What do I do when I can''t sleep?', null, null),
  (null, 'who_knows', 'Who do I call first with good news?', null, null),
  (null, 'who_knows', 'What''s my most-used emoji?', null, null),
  (null, 'who_knows', 'What would I change about my day?', null, null),
  (null, 'who_knows', 'What am I actually scared of?', null, null),
  (null, 'who_knows', 'What do I always forget?', null, null),

  -- 🔮 Guess My Answer -------------------------------------------------------
  (null, 'guess_my_answer', 'My favourite thing about you is…', null, null),
  (null, 'guess_my_answer', 'The nicest thing you''ve ever done for me was…', null, null),
  (null, 'guess_my_answer', 'If we could go anywhere tomorrow, I''d pick…', null, null),
  (null, 'guess_my_answer', 'The moment I knew was…', null, null),
  (null, 'guess_my_answer', 'The thing I''d miss most about you is…', null, null),
  (null, 'guess_my_answer', 'What I want more of from you is…', null, null),
  (null, 'guess_my_answer', 'My ideal Sunday with you is…', null, null),
  (null, 'guess_my_answer', 'The thing you do that I find most attractive is…', null, null),
  (null, 'guess_my_answer', 'What makes me feel most loved is…', null, null),
  (null, 'guess_my_answer', 'The first thing I noticed about you was…', null, null),
  (null, 'guess_my_answer', 'What I''d never change about us is…', null, null),
  (null, 'guess_my_answer', 'If I described you in one word it''d be…', null, null),

  -- 🏆 Couple Trivia ---------------------------------------------------------
  (null, 'couple_trivia', 'Where were we the first time we met?', null, null),
  (null, 'couple_trivia', 'What did we eat on our first date?', null, null),
  (null, 'couple_trivia', 'Who said "I love you" first?', null, null),
  (null, 'couple_trivia', 'What''s the first film we watched together?', null, null),
  (null, 'couple_trivia', 'What was our first argument about?', null, null),
  (null, 'couple_trivia', 'What was I wearing the first time you saw me?', null, null),
  (null, 'couple_trivia', 'What''s the longest we''ve gone without speaking?', null, null),
  (null, 'couple_trivia', 'Which song would you call ours?', null, null),
  (null, 'couple_trivia', 'Who texted first, and what did it say?', null, null),
  (null, 'couple_trivia', 'What''s the furthest we''ve travelled together?', null, null),
  (null, 'couple_trivia', 'What did I call you before the nickname stuck?', null, null),
  (null, 'couple_trivia', 'Whose family did we meet first?', null, null),

  -- ✍️ Finish My Sentence ----------------------------------------------------
  (null, 'finish_sentence', 'I feel closest to you when…', null, null),
  (null, 'finish_sentence', 'I wish we did more…', null, null),
  (null, 'finish_sentence', 'You always know how to…', null, null),
  (null, 'finish_sentence', 'I''m at my worst when…', null, null),
  (null, 'finish_sentence', 'The thing I never say out loud is…', null, null),
  (null, 'finish_sentence', 'I knew this was serious when…', null, null),
  (null, 'finish_sentence', 'You make me braver about…', null, null),
  (null, 'finish_sentence', 'If I''m quiet, it usually means…', null, null),
  (null, 'finish_sentence', 'Our house will always smell like…', null, null),
  (null, 'finish_sentence', 'In ten years I hope we still…', null, null),
  (null, 'finish_sentence', 'The best thing about a bad day is…', null, null),
  (null, 'finish_sentence', 'I''d follow you to…', null, null),

  -- 🕰️ How Well Do You Remember ---------------------------------------------
  (null, 'remember', 'What did I order the last time we ate out?', null, null),
  (null, 'remember', 'What was the last thing I complained about?', null, null),
  (null, 'remember', 'What did I wear yesterday?', null, null),
  (null, 'remember', 'What''s the last thing I said I wanted to buy?', null, null),
  (null, 'remember', 'What was the last film we started and didn''t finish?', null, null),
  (null, 'remember', 'Who did I last speak to on the phone?', null, null),
  (null, 'remember', 'What time did I go to bed last night?', null, null),
  (null, 'remember', 'What''s the last photo I took?', null, null),
  (null, 'remember', 'What did I say I was looking forward to this week?', null, null),
  (null, 'remember', 'What''s the last thing that made me laugh properly?', null, null),
  (null, 'remember', 'Where did we go the last time we went out together?', null, null),
  (null, 'remember', 'What''s the last thing I asked you to remember?', null, null),

  -- 🎭 Truth or Dare ---------------------------------------------------------
  (null, 'truth_or_dare', 'Truth: what''s something you''ve never told me?', null, null),
  (null, 'truth_or_dare', 'Dare: send me the last photo in your camera roll.', null, null),
  (null, 'truth_or_dare', 'Truth: when did you last lie to me, even a small one?', null, null),
  (null, 'truth_or_dare', 'Dare: do your impression of me. Now.', null, null),
  (null, 'truth_or_dare', 'Truth: what do you wish I''d ask you more often?', null, null),
  (null, 'truth_or_dare', 'Dare: say three things you like about yourself, out loud.', null, null),
  (null, 'truth_or_dare', 'Truth: what''s the pettiest thing you''ve been annoyed at me for?', null, null),
  (null, 'truth_or_dare', 'Dare: text someone we both know something nice, right now.', null, null),
  (null, 'truth_or_dare', 'Truth: what part of me did you not expect to love?', null, null),
  (null, 'truth_or_dare', 'Dare: record a ten-second voice note for me to keep.', null, null),
  (null, 'truth_or_dare', 'Truth: what''s the one thing you''d change about us?', null, null),
  (null, 'truth_or_dare', 'Dare: let me pick your next three songs.', null, null),
  (null, 'truth_or_dare', 'Truth: when were you last properly proud of me?', null, null),
  (null, 'truth_or_dare', 'Dare: say the thing you''ve been putting off saying.', null, null),

  -- 2️⃣ 20 Questions ---------------------------------------------------------
  (null, 'twenty_questions', 'What''s the best day you''ve ever had?', null, null),
  (null, 'twenty_questions', 'What do you worry about at 3am?', null, null),
  (null, 'twenty_questions', 'Who do you miss?', null, null),
  (null, 'twenty_questions', 'What would you do with a free year?', null, null),
  (null, 'twenty_questions', 'What are you avoiding right now?', null, null),
  (null, 'twenty_questions', 'What did you want to be at ten?', null, null),
  (null, 'twenty_questions', 'What''s your happiest memory of home?', null, null),
  (null, 'twenty_questions', 'What do you need more of at the moment?', null, null),
  (null, 'twenty_questions', 'What are you better at than you admit?', null, null),
  (null, 'twenty_questions', 'What''s the kindest thing anyone has done for you?', null, null),
  (null, 'twenty_questions', 'What would you tell your younger self?', null, null),
  (null, 'twenty_questions', 'What do you find hardest to forgive?', null, null),
  (null, 'twenty_questions', 'What makes you feel most alive?', null, null),
  (null, 'twenty_questions', 'What have you changed your mind about?', null, null),
  (null, 'twenty_questions', 'Who knows you best, apart from me?', null, null),
  (null, 'twenty_questions', 'What are you looking forward to?', null, null),
  (null, 'twenty_questions', 'What would make this year a good one?', null, null),
  (null, 'twenty_questions', 'What do you do when nobody''s watching?', null, null),
  (null, 'twenty_questions', 'What''s something you''ve never got over?', null, null),
  (null, 'twenty_questions', 'What do you want to be remembered for?', null, null),
  (null, 'twenty_questions', 'What are you most grateful for today?', null, null),
  (null, 'twenty_questions', 'What would you never do again?', null, null),

  -- 😅 Emoji Guessing --------------------------------------------------------
  (null, 'emoji_game', 'Spell our first date in emoji. They guess.', null, null),
  (null, 'emoji_game', 'Spell your favourite film in emoji.', null, null),
  (null, 'emoji_game', 'Spell what you want for dinner in emoji.', null, null),
  (null, 'emoji_game', 'Spell how your day went in emoji.', null, null),
  (null, 'emoji_game', 'Spell our song in emoji.', null, null),
  (null, 'emoji_game', 'Spell the last place we went in emoji.', null, null),
  (null, 'emoji_game', 'Spell your mood right now in three emoji.', null, null),
  (null, 'emoji_game', 'Spell me in emoji. Carefully.', null, null),
  (null, 'emoji_game', 'Spell our dream holiday in emoji.', null, null),
  (null, 'emoji_game', 'Spell what you''d do with a free weekend in emoji.', null, null),
  (null, 'emoji_game', 'Spell a memory of us in emoji.', null, null),
  (null, 'emoji_game', 'Spell your worst habit in emoji.', null, null),

  -- 🖼️ Picture Guessing -----------------------------------------------------
  (null, 'picture_game', 'Describe a photo of us without saying where. They name it.', null, null),
  (null, 'picture_game', 'Describe the last photo you took of me.', null, null),
  (null, 'picture_game', 'Describe your favourite photo of us in one sentence.', null, null),
  (null, 'picture_game', 'Describe a photo from before we met.', null, null),
  (null, 'picture_game', 'Describe the worst photo of you that exists.', null, null),
  (null, 'picture_game', 'Describe a photo you''ve never shown me.', null, null),
  (null, 'picture_game', 'Describe your phone wallpaper without showing it.', null, null),
  (null, 'picture_game', 'Describe a photo that always makes you laugh.', null, null),
  (null, 'picture_game', 'Describe the first photo we ever took together.', null, null),
  (null, 'picture_game', 'Describe a photo you''d frame.', null, null)
on conflict do nothing;
